# Generated by Django 5.2.7 on 2025-10-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la marca')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo_marca', models.CharField(choices=[('EQUIPOS', 'Equipos de Cómputo'), ('COMPONENTES', 'Componentes'), ('SOFTWARE', 'Software'), ('ACCESORIOS', 'Accesorios'), ('CONSUMIBLES', 'Consumibles')], max_length=12, verbose_name='Tipo de marca')),
                ('pais_origen', models.CharField(blank=True, max_length=100, null=True, verbose_name='País de origen')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio web oficial')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/logos/', verbose_name='Logo')),
                ('activa', models.BooleanField(default=True, verbose_name='Marca activa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipo', models.CharField(max_length=20, unique=True, verbose_name='Código del equipo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del equipo')),
                ('tipo_equipo', models.CharField(choices=[('DESKTOP', 'Computador de Escritorio'), ('LAPTOP', 'Computador Portátil'), ('SERVER', 'Servidor'), ('PRINTER', 'Impresora'), ('SCANNER', 'Escáner'), ('NETWORK', 'Equipo de Red'), ('MONITOR', 'Monitor'), ('UPS', 'UPS'), ('OTROS', 'Otros')], max_length=10, verbose_name='Tipo de equipo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial', models.CharField(max_length=100, unique=True, verbose_name='Número de serie')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de compra')),
                ('estado_fisico', models.CharField(choices=[('NUEVO', 'Nuevo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DAÑADO', 'Dañado'), ('EN_REPARACION', 'En Reparación')], max_length=15, verbose_name='Estado físico')),
                ('especificaciones', models.TextField(verbose_name='Especificaciones técnicas')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Equipo activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente propietario')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
                'ordering': ['codigo_equipo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=20, unique=True, verbose_name='Código del producto')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('ACCESORIOS', 'Accesorios'), ('CONSUMIBLES', 'Consumibles'), ('COMPONENTES', 'Componentes'), ('SERVICIOS', 'Servicios')], max_length=15, verbose_name='Categoría')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de venta')),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Margen de ganancia (%)')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=1, verbose_name='Stock mínimo')),
                ('stock_maximo', models.PositiveIntegerField(default=100, verbose_name='Stock máximo')),
                ('unidad_medida', models.CharField(default='Unidad', max_length=20, verbose_name='Unidad de medida')),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación en almacén')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('DESCONTINUADO', 'Descontinuado'), ('PROXIMAMENTE', 'Próximamente')], default='DISPONIBLE', max_length=15, verbose_name='Estado')),
                ('especificaciones', models.TextField(blank=True, null=True, verbose_name='Especificaciones técnicas')),
                ('garantia_meses', models.PositiveIntegerField(default=12, verbose_name='Garantía (meses)')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='URL amigable')),
                ('meta_descripcion', models.TextField(blank=True, max_length=160, null=True, verbose_name='Meta descripción')),
                ('palabras_clave', models.CharField(blank=True, max_length=255, null=True, verbose_name='Palabras clave')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca', verbose_name='Marca')),
                ('proveedor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor', verbose_name='Proveedor principal')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
    ]
