# Generated by Django 5.2.7 on 2025-10-07 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('LOGIN_FALLIDO', 'Intento Fallido'), ('RECUPERACION', 'Recuperación de Contraseña'), ('CAMBIO_PASSWORD', 'Cambio de Contraseña')], max_length=20, verbose_name='Tipo de Acción')),
                ('username', models.CharField(max_length=150, verbose_name='Usuario')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Navegador')),
                ('exitoso', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historial de Accesos',
                'db_table': 'historial_accesos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrador'), ('ADMINISTRADOR', 'Administrador'), ('CLIENTE', 'Cliente'), ('TECNICO', 'Técnico'), ('PROVEEDOR', 'Proveedor')], max_length=20, verbose_name='Tipo de Usuario')),
                ('telefono', models.CharField(blank=True, max_length=17, null=True, verbose_name='Teléfono')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=12, verbose_name='Estado')),
                ('puede_crear_usuarios', models.BooleanField(default=False, verbose_name='Puede crear usuarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'perfil_usuario',
            },
        ),
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código de Verificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Solicitud')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Recuperación',
                'verbose_name_plural': 'Tokens de Recuperación',
                'db_table': 'tokens_recuperacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
