# Generated by Django 5.2.7 on 2025-10-03 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_afectada', models.CharField(max_length=100, verbose_name='Tabla afectada')),
                ('registro_id', models.PositiveIntegerField(verbose_name='ID del registro')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('razon_cambio', models.TextField(blank=True, null=True, verbose_name='Razón del cambio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.administrador', verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Historial de Cambios',
                'verbose_name_plural': 'Historial de Cambios',
                'db_table': 'historial_cambios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('SUCCESS', 'Éxito')], max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('SISTEMA', 'Sistema'), ('VENTA', 'Venta'), ('SERVICIO', 'Servicio'), ('INVENTARIO', 'Inventario'), ('FACTURACION', 'Facturación'), ('GARANTIA', 'Garantía')], max_length=15, verbose_name='Categoría')),
                ('para_administradores', models.BooleanField(default=False, verbose_name='Para administradores')),
                ('para_tecnicos', models.BooleanField(default=False, verbose_name='Para técnicos')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('factura_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.factura', verbose_name='Factura referencia')),
                ('orden_servicio_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.ordenservicio', verbose_name='Orden servicio referencia')),
                ('usuario_especifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador', verbose_name='Usuario específico')),
                ('venta_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.venta', verbose_name='Venta referencia')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
