# Generated by Django 5.2.7 on 2025-10-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitSoft', '0001_initial'),
        ('administrador', '0004_detallecompra_detalleventa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificacin', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='factura_ref',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='orden_servicio_ref',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='venta_ref',
        ),
        migrations.AlterField(
            model_name='historialcambios',
            name='razon_cambio',
            field=models.TextField(blank=True, null=True, verbose_name='Razn del cambio'),
        ),
        migrations.AlterField(
            model_name='historialcambios',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.administrador', verbose_name='Usuario que realiz el cambio'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(choices=[('SISTEMA', 'Sistema'), ('VENTA', 'Venta'), ('SERVICIO', 'Servicio'), ('INVENTARIO', 'Inventario'), ('FACTURACION', 'Facturacin'), ('GARANTIA', 'Garanta')], max_length=15, verbose_name='Categora'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacin'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False, verbose_name='Leda'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='para_tecnicos',
            field=models.BooleanField(default=False, verbose_name='Para tcnicos'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('INFO', 'Informacin'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('SUCCESS', '‰xito')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Ttulo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador', verbose_name='Usuario especfico'),
        ),
    ]
