# Generated by Django 5.2.7 on 2025-10-09 11:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('compras', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del servicio')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción del servicio')),
                ('categoria', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('REDES', 'Redes'), ('MANTENIMIENTO', 'Mantenimiento'), ('INSTALACION', 'Instalación'), ('CONSULTORIA', 'Consultoría')], max_length=15, verbose_name='Categoría')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('tiempo_estimado_horas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tiempo estimado (horas)')),
                ('requiere_materiales', models.BooleanField(default=False, verbose_name='Requiere materiales')),
                ('especificaciones', models.TextField(blank=True, null=True, verbose_name='Especificaciones técnicas')),
                ('herramientas_requeridas', models.TextField(blank=True, null=True, verbose_name='Herramientas requeridas')),
                ('prerequisitos', models.TextField(blank=True, null=True, verbose_name='Prerequisitos')),
                ('garantia_dias', models.PositiveIntegerField(default=30, verbose_name='Garantía (días)')),
                ('activo', models.BooleanField(default=True, verbose_name='Servicio activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Servicio Técnico',
                'verbose_name_plural': 'Servicios Técnicos',
                'db_table': 'servicios_tecnicos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True, verbose_name='Número de orden')),
                ('descripcion_problema', models.TextField(verbose_name='Descripción del problema')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico técnico')),
                ('solucion_aplicada', models.TextField(blank=True, null=True, verbose_name='Solución aplicada')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('fecha_estimada_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha estimada de entrega')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega real')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('FACTURADA', 'Facturada')], default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=8, verbose_name='Prioridad')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo mano de obra')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo repuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo', verbose_name='Equipo')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.tecnico', verbose_name='Técnico asignado')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'db_table': 'ordenes_servicio',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
