# Generated by Django 5.2.7 on 2025-10-09 11:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('PAS', 'Pasaporte')], max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón social')),
                ('tipo_cliente', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Jurídica')], default='NATURAL', max_length=10, verbose_name='Tipo de cliente')),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nombres', 'apellidos'],
            },
        ),
    ]
