# Generated by Django 5.2.7 on 2025-10-09 11:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compra', models.CharField(max_length=20, unique=True, verbose_name='Número de compra')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('fecha_cotizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cotización')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('fecha_pedido', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pedido')),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha entrega estimada')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha entrega real')),
                ('estado', models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('COTIZACION', 'Cotización'), ('APROBADA', 'Aprobada'), ('PEDIDO_ENVIADO', 'Pedido Enviado'), ('RECIBIDA_PARCIAL', 'Recibida Parcial'), ('RECIBIDA_COMPLETA', 'Recibida Completa'), ('FACTURADA', 'Facturada'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='SOLICITUD', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Descuento')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Impuestos')),
                ('costos_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costos de envío')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total')),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito')], max_length=15, null=True, verbose_name='Método de pago')),
                ('numero_factura_proveedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número factura proveedor')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('condiciones_pago', models.TextField(blank=True, null=True, verbose_name='Condiciones de pago')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra', verbose_name='Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'db_table': 'detalles_compra',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('especialidades', models.TextField(verbose_name='Especialidades técnicas')),
                ('nivel_experiencia', models.CharField(choices=[('JUNIOR', 'Junior'), ('INTERMEDIO', 'Intermedio'), ('SENIOR', 'Senior'), ('ESPECIALISTA', 'Especialista')], max_length=12, verbose_name='Nivel de experiencia')),
                ('certificaciones', models.TextField(blank=True, null=True, verbose_name='Certificaciones')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('estado_actual', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('DESCANSO', 'En descanso'), ('VACACIONES', 'De vacaciones'), ('INCAPACITADO', 'Incapacitado')], default='DISPONIBLE', max_length=12, verbose_name='Estado actual')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Calificación promedio')),
                ('servicios_completados', models.PositiveIntegerField(default=0, verbose_name='Servicios completados')),
                ('activo', models.BooleanField(default=True, verbose_name='Técnico activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'db_table': 'tecnicos',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.tecnico', verbose_name='Solicitado por'),
        ),
    ]
