# Generated by Django 5.2.7 on 2025-10-09 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], default='NIT', max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre comercial')),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('categoria_principal', models.CharField(choices=[('EQUIPOS', 'Equipos de Cómputo'), ('COMPONENTES', 'Componentes y Partes'), ('SOFTWARE', 'Software y Licencias'), ('ACCESORIOS', 'Accesorios'), ('CONSUMIBLES', 'Consumibles'), ('SERVICIOS', 'Servicios')], max_length=15, verbose_name='Categoría principal')),
                ('contacto_principal', models.CharField(max_length=100, verbose_name='Contacto principal')),
                ('telefono_contacto', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email contacto')),
                ('condiciones_pago', models.TextField(blank=True, null=True, verbose_name='Condiciones de pago')),
                ('tiempo_entrega_dias', models.PositiveIntegerField(default=1, verbose_name='Tiempo de entrega (días)')),
                ('calificacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Calificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Proveedor activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['razon_social'],
            },
        ),
    ]
